server:
  port: 8088
# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  application:
    name: user-service
logging:
  config: classpath:logback.xml
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8005/xxl-job-admin
    accessToken: ''
    executor:
      appname: xxl-job-executor-user
      address: ''
      ip: ''
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.xml



